# -*- coding:utf-8-unix; mode:yaml; -*-

title: "電卓片手に"
email: keiichiro.ui at gmail.com
author: "Keiichiro Ui"
description: ねこほしい

source: src
destination: public

url: "http://k-ui.jp"
baseurl: ""
permalink: "/blog/:year/:month/:day/:title/"
timezone: "Japan"

markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

highlighter: rouge

defaults:
  -
    scope:
      type: posts
    values:
      layout: post

qiita_id: k_ui
github_id: kui
twitter_id: k_ui
tumblr_id: k-ui
