# -*- coding:utf-8-unix; mode:yaml; -*-

title: "電卓片手に"
email: #keiichiro.ui@gmail.com
author: "Keiichiro Ui"
description: ねこほしい

source: src
destination: public

url: "http://k-ui.jp"
baseurl: ""
permalink: "/blog/:year/:month/:day/:title/"
timezone: "Japan"

markdown: redcarpet
redcarpet:
  extensions:
    - with_toc_data
    - tables
    - fenced_code_blocks
    - autolink

browserify:
  command: "$(npm bin)/browserify -t babelify -"

# Additional Info
qiita_id: k_ui
github_id: kui
