# -*- coding:utf-8-unix; mode:yaml; -*-

title: "電卓片手に"
email: #keiichiro.ui@gmail.com
author: "Keiichiro Ui"
description: ねこほしい

source: src
destination: public
plugins_dir: plugins

date_format: "%Y年 %m月 %d日"
url: "http://k-ui.jp"
