#!/bin/bash
set -eu
cd "$(dirname "$0")/.."

DIR="$(pwd)"
DEFAULT_DEST="public"
NEW_DEST="new-public"

main() {
    build
    logrotate --state=logrotate.state <(cat <<EOF
"$DIR/cron.log" {
  mounthly
  missingok
  rotate 6
  compress
}
EOF
)
}

build() {
    command git fetch --all >/dev/null
    local local_ref="$(command git rev-parse '@')"
    local remote_ref="$(command git rev-parse '@{u}')"

    if [[ "$local_ref" = "$remote_ref" ]]; then
        return
    fi

    git log --oneline "$local_ref"..."$remote_ref"

    git pull >/dev/null

    rm -fr "$NEW_DEST"
    make build DEST="$NEW_DEST"

    if [[ -e "$DEFAULT_DEST" ]]; then
        rm -fr "$DEFAULT_DEST"
    fi
    mv "$NEW_DEST" "$DEFAULT_DEST"
}

timestamp() {
    perl -pe 'use POSIX;$t=POSIX::strftime("%FT%T%z",localtime);s/^/$t | /;'
}

main 2>&1 | timestamp | tee -a cron.log
exit ${PIPESTATUS[0]}
