#!/bin/bash
set -eu

cd "$(dirname "$0")/.."

if [[ $# -eq 0 || -z "$1" ]]; then
    printf "Input title: "
    read title
    if [[ -z "$title" ]]; then
        printf "Abort: empty title\n"
        exit 1
    fi
else
    title="$1"
fi

date="$(date +'%F %T%z')"

year="$(date +%Y)"
month="$(date +%m)"
prefix="$(date +%F)"
escaped_title="$(perl -pe "chomp; s/\s/_/g" <<< "$title")"
file="src/_posts/$year/$month/$prefix-$escaped_title.md"

mkdir -p "$(dirname "$file")"

if [[ -e "$file" ]]; then
    printf "Already exists: %s\n" "$file"
    printf "Overwrite? y/n [n]: "
    read answer

    if [[ "$answer" != "y" ]]; then
        printf "Abort\n"
        exit
    fi
fi

cat <<EOF > "$file"
---
title: $title
date: $date
---

EOF

printf "Create new post: %s\n" "$file"
if which editor &>/dev/null; then
    printf "Edit: %s\n" "$file"
    "${EDITOR:-edit}" "$file"
fi
