name: Deploy

on:
  push:
    branches:
      - master
      - "post/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: Build
        run: deno task build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=k-ui-jp
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
